# Color scheme
import = ["~/.config/alacritty/rose-pine-moon.toml"]

# Set font size
[font]
size = 12

# Set font style
[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

# Autostart shell
[shell]
program = "nu"
