# Color scheme
import = ["/home/arttu/.config/alacritty/themes/rose-pine/rose-pine-moon.toml"]

# Set font size
[font]
size = 12

# Set font style
[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

# Autostart fish
[shell]
program = "/usr/bin/fish"
